# Generated by Django 5.2.5 on 2025-09-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When doctor accepted the appointment', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When appointment was completed', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Notes for the patient', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preparation_instructions',
            field=models.TextField(blank=True, help_text='Instructions for patient preparation', null=True),
        ),
    ]
