# Generated by Django 5.2.8 on 2025-11-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment_accepted_at_appointment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='available', max_length=10),
        ),
    ]
